apiVersion: v1
kind: Service
metadata:
  name: chat-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: chat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
